### ISSUE TITLE
SIPAssembler is creating a temp file under temp directory but not removing the tmp file after calling sipAssembler.end()

### ISSUE THREAD

**Issue by AmuthanGit** [Enterprise-Content-Management/infoarchive-sip-sdk#59]
Hi Team,

I am using SIPAssembler with FileBuffer to create SIP packages for CSV files. I am using this method as we have huge sized CSV files to be processed and we are able to process them.
Now the SIPAssembler is creating a temp file in Windows/Linux tmp directory and not removing that after finishing the SIP creation. Due to which the tmp folder is running out of free space.

Below is the code we used to created SIP Packages.

public void assembler(final List<CSVData> csvRecords, final PackagingInformationFactory factory,
			final ResponseBean status, List<File> sipFiles, PdiAssembler<CSVData> pdiAssembler, String fileName)
			throws SipCreationException, IOException {
		SipAssembler<CSVData> sipAssembler = 
				new SipAssembler<>
		(factory, pdiAssembler, new NoHashAssembler(), new DataBufferSupplier<>(FileBuffer.class),ContentAssembler.ignoreContent());
				File sipFile=new File(CsvSipConstants.OUTPUT_PATH,CsvSipConstants.SIP_FILE_PREFIX+fileName+"_"+getRandomNumber()+".zip");
			sipAssembler.start(new FileBuffer(sipFile));
			for(CSVData record: csvRecords) {
				sipAssembler.add(record);
			}
				sipAssembler.end();
				LOGGER.info("Sip file : "+sipFile);
				sipFiles.add(sipFile);
			}
			LOGGER.info("SIP package created");
	}

Could you please help me with this?

Regards,
Amuthan

**Comment by kovaloid** [comment]
Hi @AmuthanGit ,

Did you eventually succeed in creating the SIP file?
And the only problem is that the temporary file is not deleted?
Have you tried to delete it manually?

Regards,
Artem

**Comment by AmuthanGit** [comment]
Hi Artem,

Yes,  I am able to create SIP packages.
Post the sip creation I am deleting tmp files manually to free up the space
now.
I believe the tmp files should get deleted by the SIP SDK once SIP file is
created.

**Comment by kovaloid** [comment]
@AmuthanGit ,
Yes, it seems like a bug.
When we create a temporary file, we need to make sure that it will be deleted after.
I'll fix this issue soon.

**Comment by AmuthanGit** [comment]
Thank you

**Comment by AmuthanGit** [comment]
Could you please mention when the fix will be available? approximately.

regards
Araamuthan

**Comment by kovaloid** [comment]
@AmuthanGit I suspect the fix will be available today.

**Comment by kovaloid** [comment]
@AmuthanGit the issue has been fixed in version 12.1.5

**Comment by AmuthanGit** [comment]
Hi @kovaloid,

I have tested this issue in 12.1.5 & 12.1.6 releases but the issue is still persisting.
After the SIP creation, SIPAssembler is no deleting the temp file.

regards,
Araamuthan

**Comment by AmuthanGit** [comment]
Hi @kovaloid <https://github.com/kovaloid>,

I have tested this issue in 12.1.5 & 12.1.6 releases but the issue is still
persisting.
After the SIP creation, SIPAssembler is not deleting the temp file. Could you please check this once?

regards,
Araamuthan
